sudo: false

language: node_js

node_js:
  - "5"

env:
  global:
    - NPM_CONFIG_PROGRESS="false"
  matrix:
    - RUBY_VERSION=2.2

before_install:
  # Remove ./node_modules/.bin from PATH so node-which doesn't replace Unix which and cause RVM to barf. See https://github.com/travis-ci/travis-ci/issues/5092
  - export PATH=$(python -c 'from sys import argv;from collections import OrderedDict as od;print(":".join(od((p,None) for p in argv[1].split(":") if p.startswith("/")).keys()))' "$PATH")
  - rvm install $RUBY_VERSION
  - rvm use $RUBY_VERSION --fuzzy
  - export GEMDIR=$(rvm gemdir)

install:
  - travis_retry npm install -g grunt-cli
  - travis_retry npm install
  - travis_retry bundle install --without development --deployment --jobs=3

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules
    - vendor/bundle
