name:               MPC-HC
description:        MPC-HC, the free, open source media player for Windows

markdown:           kramdown
highlighter:        false

gems:
  - jekyll-feed
  - jekyll-sitemap

exclude:
# we generate those files ourselves
- "*.css"
- "*.js"
- "_old"

# paginate
paginate:           10
paginate_path:      archive/page:num

# permalinks
permalink:          pretty

# server
source:             source
destination:        _site
port:               8000
url:                https://mpc-hc.org
encoding:           UTF-8

# custom variables
version:
  short:            1.7.10
  long:             1.7.10.0
  hash:             "d911f14"
  date:             "14 November 2015"

feed:
  description:      Latest information about the MPC-HC project.
  path:             rss.xml
  url:              https://mpc-hc.org

news_limit:         5
