markdown:       kramdown
pygments:       false

exclude:
# we generate those files ourselves
- "*.css"
- "*.js"
- "_old"

# permalinks
permalink:      pretty

# server
source:         ./source/
destination:    ./_site/
port:           8000
baseurl:        /

# custom variables
version:
  short:        1.7.3
  long:         1.7.3.0
  hash:         "cb22afa"

name:           MPC-HC
url:            "http://mpc-hc.org"
rss_limit:      10
news_limit:     5
