markdown:       kramdown
pygments:       false
safe:           true

exclude:
- "*.css"
- "*.js"

# permalinks
permalink:      pretty

# server
source:         ./source
destination:    ./_site
port:           8000
baseurl:        /

# custom variables
version:
  short:        1.7.1
  long:         1.7.1.0
  hash:         "9ae7b7c"

url:            "http://mpc-hc.org"
trac_url:       "https://trac.mpc-hc.org/"
intertrac:      "https://trac.mpc-hc.org/intertrac/%23"
rss_limit:      10
news_limit:     4
