markdown:           kramdown
highlighter:        false
gems:
  - jekyll-sitemap

exclude:
# we generate those files ourselves
- "*.css"
- "*.js"
- "_old"

# paginate
paginate:           10
paginate_path:      archive/page:num

# permalinks
permalink:          pretty

# server
source:             ./source/
destination:        ./_site/
port:               8000
baseurl:            /

# custom variables
version:
  short:            1.7.8
  long:             1.7.8.0
  hash:             "6fcba1b"
  date:             "25 January 2015"

name:               MPC-HC
feed_description:   Latest information about the MPC-HC project.
url:                "http://mpc-hc.org"
rss_limit:          10
news_limit:         5
