name:               MPC-HC
description:        MPC-HC, the free, open source media player for Windows
lang:               en

markdown:           kramdown
highlighter:        false

plugins:
  - jekyll-avatar
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  # we generate those files ourselves
  - "*.css"
  - "*.js"

# https://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "news"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# paginate
paginate:           10
paginate_path:      archive/page:num

# permalinks
permalink:          pretty

# server
source:             source
destination:        _site
port:               8000
url:                https://mpc-hc.org
encoding:           UTF-8

# custom variables
version:
  short:            1.7.11
  long:             1.7.11.0
  hash:             "b989276ec"
  date:             "06 March 2017"

feed:
  description:      Latest information about the MPC-HC project.
  path:             rss.xml
  url:              https://mpc-hc.org

news_limit:         5
