markdown:           kramdown
highlighter:        false

exclude:
# we generate those files ourselves
- "*.css"
- "*.js"
- "_old"

# permalinks
permalink:          pretty

# server
source:             ./source/
destination:        ./_site/
port:               8000
baseurl:            /

# custom variables
version:
  short:            1.7.7
  long:             1.7.7.0
  hash:             "46ce9d6"

name:               MPC-HC
feed_description:   Latest information about the MPC-HC project.
url:                "http://mpc-hc.org"
rss_limit:          10
news_limit:         5
