# https://www.appveyor.com/docs/appveyor-yml

version: "{build}"

clone_depth: 10

environment:
  matrix:
    - ruby_folder_version: "23"
      ruby_gems_folder: "2.3.0"
      platform: "x86"
    #- ruby_folder_version: "23-x64"
    #  ruby_gems_folder: "2.3.0"
    #  platform: "x64"

install:
  - SET "PATH=C:\Ruby%ruby_folder_version%\bin;%PATH%"
  # Bundler downgrade should be removed when the issue is fixed upstream
  - gem uninstall bundler -x
  - gem install bundler -v "=1.10.6" --no-document
  - bundle install --retry 3 --jobs=%NUMBER_OF_PROCESSORS% --clean --deployment
  - ps: Install-Product node "4" $env:platform
  - npm config set spin false
  - npm install

build: off

test_script:
  - ruby -v
  - gem -v
  - bundle -v
  - node -v
  - npm -v
  - java -version
  - npm test

matrix:
  fast_finish: true

cache:
  - 'node_modules -> appveyor.yml,package.json'
  - 'vendor\bundle -> appveyor.yml,Gemfile,Gemfile.lock'
